title: Wonbeen Yoon
description: Undergraduate Student
site_title: '@wbyoon - Wonbeen Yoon'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: wbyoon2002
blog_url: https://blog.naver.com/ericyoon1130
email: wbyoon@snu.ac.kr
keybase_username: wbyoon
twitter_username: wb_yoon_2002
reddit_username: wbyoon

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 