title: Wonbeen Yoon
description: Undergraduate Student
site_title: '@wbyoon - Wonbeen Yoon'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: wbyoon
blog_url: https://www.wbyoon.com
email: wbyoon@snu.ac.kr
keybase_username: wbyoon
twitter_username: wbyoon
reddit_username: wbyoon

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 